title: My Blog
description: A blog about art, music, projects, and life
author: James
baseurl: "/blog-site"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
future: true

