title: My Blog
description: A blog about art, music, and life
author:
  name: James
remote_theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
future: true
